name: Update Readme and ics workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: create readme
      run: |
        python create_readme.py
    - name: Check for changes
      run: |
        git diff --quiet || { echo "No changes to commit. Exiting..."; exit 0; }
    - name: Commit
      run: |
        git config --global user.name 'ActionBOT'
        git config --global user.email 'action@totaly.made.up.email.yxz'
        git add .
        git commit -m "update"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
